### ISSUE TITLE
Limiting searches to one item returned

### ISSUE THREAD

**Issue by ChristopherGranier** [osrsbox/osrsbox-api#11]
For example, when I do a search for a "Vial" (https://api.osrsbox.com/items?where={"name":"Vial"}) it returns multiple items. Even using "duplicates":"true" returns two results. 

Is there a way to ask the result to only return the top item?

**Comment by ChristopherGranier** [comment]
Disregard. 
Issue was resolved by adding &max_results=1 on the end of my string.

Example URL: https://api.osrsbox.com/items?where={"name":"Vial"}&max_results=1

**Comment by osrsbox** [comment]
Glad you solved this. Just wanted to reply to clarify a couple things that may help. Your original query:
```
https://api.osrsbox.com/items?where={"name":"Vial","duplicate":false}
```
This returns multiple items because there are multiple items that have the name `Vial` in-game. If you look at the results, each item is not a duplicate... and they all have different `wiki_name` property valies. This was a hard design choice to implement - but technically, none of these items are duplicates... even when they have the same name (in the game). If you wanted an actual Vial, you could also use:
```
https://api.osrsbox.com/items?where={"wiki_name":"Vial","duplicate":false}
```
The only difference is using `wiki_name` instead of just `name`. I hope this makes sense, and clarifies why there are multiple items with the name `Vial` - even when the `duplicate` option is used.

One final thought, there are times that the first item returned (based on item ID starting at 0) will not be the item you are probably looking for - so just keep that in mind. Apart from that scenario, the `max_results` parameter will work fine :)

**Comment by ChristopherGranier** [comment]
Yeah that's what I found when looking through the JSON. For my example, they were all different items just named vial. 

I did consider that the first result may not be what I'm looking for, but I believe that would be fine for the project I'm doing. I'm building a sort of GE tracker website and I'm using this API to pull details about items and most importantly Item ID's. 

This project will only be presented to my professor, so I just need to make sure it doesn't break when running haha. 

Thanks for the advice!

**Comment by osrsbox** [comment]
Ah... after knowing you are only after GE items, this may help:
```
https://api.osrsbox.com/items?where={"name":"Vial","tradeable_on_ge":true}
```
The `tradeable_on_ge` property is 100% accurate (very happy about this!). Tested numerous times, and compared against official JaGeX GE, and OSBuddy Exchange. I use it a lot.

**Comment by ChristopherGranier** [comment]
Well, you just made my life so much easier! 

Thank you!!
