### ISSUE TITLE
API endpoint slow from PHP?

### ISSUE THREAD

**Issue by brndto** [osrsbox/osrsbox-api#18]
Any time I try to hit one of the item endpoints it takes about 30-60 seconds before I seem to get a response
Endpoint URL example:
`https://api.osrsbox.com/items?where={%20%22id%22:%20%222%22}&projection={%20%22name%22:%201%20}`

Code example:
```
        $ci = curl_init();
        curl_setopt($ci, CURLOPT_URL, 'https://api.osrsbox.com/items?where={"id" : "' . $bank_row['item_id'] . '"}&projection={"name": 1}');
        curl_setopt($ci, CURLOPT_RETURNTRANSFER, 1);
        $item_json = curl_exec($ci);
        var_dump($item_json);
        curl_close($ci);
```

**Comment by osrsbox** [comment]
Hey @brndto
I don't think this problem is on my side. Or couldn't see why any configs I have on the webserver/appserver would solely affect PHP performance. I can run the query you provided with wget, curl (cmdline version), Python requests, and in-browser - and get a pretty good performance. About 1 second response time, or so (estimate). Makes me think it is (most likely) a curl in PHP problem. A quick Google search found lots of similar problems to yours (search term used: php curl performance). There is all sorts of advice I read - including how curl is initialized, DNS lookup etc. But I am not very well versed in PHP.

Guessing you can make the same request using the browser, or something like wget? How is the performance doing that?

**Comment by osrsbox** [comment]
Considering this issue stale and closing. Doesn't seem relevant to this API implementation. But please feel free to reopen it if you have further questions.
